### ISSUE TITLE
react-monaco-editor 

### ISSUE THREAD

**Issue by yjs-yang** [hzm0321/apaas-front-doc#9]
你好 看了您的这篇文章react-monaco-editor 常用配置项
想知道您 这个FormatFunctionProps类型定义是什么样的

**Comment by hzm0321** [comment]
export interface FormatFunctionProps {
  word: string;
  match: string;
  children: FormatFunctionProps[];
  remark?: string;
  parentWord?: string;
}

**Comment by yjs-yang** [comment]
谢谢
